(()=>{
  const L=(teach,points,examples,practice)=>({teach,points,examples:examples.map(item=>item.split("||")),practice:practice.map(item=>item.split("||"))});
  window.BRIDGE_LESSON_MATERIALS=[
    [
      L("先判断自己是否真的掌握单词：能读、能说中文、能在句子中使用才算会。只觉得眼熟不能算掌握。",["遮住中文，在3秒内说出词义","遮住英文，根据中文拼写","把不确定词分为发音、拼写、词义三类"],["library||图书馆||先按音节 li-bra-ry 读，再记地点含义","weather||天气||注意不要和 whether（是否）混淆","healthy||健康的||形容词，可放在名词前或be动词后"],["“图书馆”的英文是什么？||library||注意中间是 bra，不是 ber。","写出 weather 的中文意思。||天气||whether 才表示“是否”。","healthy 是什么词性？||形容词||它描述人或事物的状态。"]),
      L("拼读不是背字母名称，而是把字母或字母组合对应到声音，再把声音合成单词。先慢读，再自然连读。",["短元音通常声音短促：a/e/i/o/u","元音字母加不发音e常形成长元音","sh、ch、th、ph等组合通常共同表示一个音"],["cap / cape||帽子 / 斗篷||末尾e让a从短音变成长音","ship / sheep||轮船 / 绵羊||重点区别 /ɪ/ 和 /iː/","thin / this||瘦的 / 这个||th在两个词中的发音不同"],["哪一个词含长元音：cap 还是 cape？||cape||末尾不发音e提示前面的a读字母音。","ship 与 sheep 的主要区别是什么？||元音长短不同||ship是短音，sheep是长音。","ph 常发什么音？||/f/||例如 photo、phone。"]),
      L("近形词必须同时比较拼写、发音和句意。做题时用手指从左到右核对每一个字母，再把词放回句子。",["right右边；light灯、轻的；night夜晚","read读；red红色；ride骑","there那里；three三；these这些"],["Turn right at the school.||在学校处右转。||right和方向搭配","Please turn on the light.||请打开灯。||light在这里是名词","There are three books.||那里有三本书。||there和three同时出现但作用不同"],["Please turn on the ____.||light||turn on the light是打开灯。","I can ____ a bike.||ride||ride a bike是骑自行车。","____ are my pencils.||These||these表示“这些”，后接复数。"]),
      L("记词卡时必须加入词性和完整句子。一个单词至少完成：听2遍、读3遍、遮住回忆1次、口头造句1句。",["名词要记是否可数及复数","动词要记过去式或常见搭配","形容词要记它描述什么"],["plan — plans||计划||可数名词，复数加s","travel — travelled/traveled||旅行||动词，注意过去式拼写","exciting||令人兴奋的||通常描述事情"],["plan 的复数是什么？||plans||一般直接加s。","travel 的过去式可写什么？||travelled||英式英语常双写l再加ed。","exciting通常描述人还是事情？||事情||人感到兴奋常用excited。"]),
      L("周测后最重要的不是分数，而是找错因。每道错题标记为：词义不懂、拼写混淆、规则不会、审题错误或不会使用。",["写出正确答案","用一句中文说明错误原因","隔一天重新独立完成同类题"],["I went to school yesterday.||我昨天去上学。||yesterday提示一般过去时","How much water do you need?||你需要多少水？||water不可数，用much","She is taller than me.||她比我高。||than提示比较级"],["yesterday通常提示什么时态？||一般过去时||动作已经发生。","water前询问数量用many还是much？||much||water是不可数名词。","tall的比较级是什么？||taller||单音节词通常加er。"])
    ],
    [
      L("a、an都表示“一个”，只用于可数名词单数。判断a还是an要听后面单词开头的声音，而不是只看字母。the表示说话双方都知道的特定事物。",["辅音音素前用a","元音音素前用an","第二次提到或特指时用the"],["a university||一所大学||university开头读/juː/，是辅音音素","an hour||一小时||h不发音，开头是元音音素","I see a dog. The dog is white.||我看见一只狗，那只狗是白色的。||第二次提到用the"],["____ English book||an||English以元音音素开头。","____ useful book||a||useful开头读/juː/。","I see a cat. ____ cat is black.||The||第二次提到这只猫。"]),
      L("可数名词能直接数出一个、两个；不可数名词通常不能直接按个数，需要借助容器或单位。复数变化要看词尾。",["一般加-s或-es","辅音字母+y变y为i加es","部分f/fe变ves，还有不规则形式"],["two boxes||两个盒子||以x结尾加es","three families||三个家庭||family变families","some bread||一些面包||bread不可数，不加s"],["box的复数是什么？||boxes||以x结尾加es。","child的复数是什么？||children||这是不规则复数。","bread可以写成breads表示几块面包吗？||不可以||一般用pieces of bread。"]),
      L("some和any都可表示“一些”。一般肯定句用some，否定句和一般疑问句用any；表示希望得到肯定回答的请求可以用some。",["many修饰可数名词复数","much修饰不可数名词","a few与a little表示少量但仍有一些"],["There are some apples.||有一些苹果。||肯定句","Do you have any milk?||你有牛奶吗？||一般疑问句","Would you like some tea?||你想喝点茶吗？||礼貌邀请常用some"],["How ____ books are there?||many||books是可数名词复数。","How ____ juice do you want?||much||juice不可数。","I don't have ____ pencils.||any||否定句通常用any。"]),
      L("代词要和它代替的人或物保持一致。主格作主语，宾格放在动词或介词后；物主代词表示“谁的”。",["I—me—my—mine","he—him—his—his","they—them—their—theirs"],["She helps me.||她帮助我。||me作help的宾语","This is my book.||这是我的书。||my后面必须接名词","The book is mine.||这本书是我的。||mine后面不再接名词"],["Please give it to ____.（我）||me||介词to后用宾格。","This is ____ bag.（她的）||her||后面有bag，用形容词性物主代词。","The blue bike is ____.（他们的）||theirs||空格后没有名词。"]),
      L("订正名词和代词题时，先圈名词，再判断可数性、数量和代词在句中的位置。把正确答案放回完整句子朗读。",["先看空格后有没有名词","再看主语是单数还是复数","最后检查句意是否明确"],["These children are playing.||这些孩子正在玩。||these和children都为复数","Her mother gives her a gift.||她妈妈给她一份礼物。||第一个her修饰名词，第二个her作宾语","There is some rice.||有一些米饭。||rice不可数，be动词用is"],["These ____ are new.（手表）||watches||watch复数加es。","Tom and I are friends. ____ play together.||We||Tom and I用we代替。","There ____ some water.||is||water不可数，视为单数。"])
    ],
    [
      L("一般现在时表示习惯、经常发生的事或客观事实。主语是he、she、it或单个人名时，实义动词通常变第三人称单数。",["频率词：often、usually、every day","否定：do not / does not + 动词原形","疑问：Do / Does + 主语 + 动词原形"],["She walks to school every day.||她每天步行上学。||she后walk加s","Does he like music?||他喜欢音乐吗？||does后like用原形","The sun rises in the east.||太阳从东方升起。||客观事实"],["My father ____ TV every evening.（watch）||watches||father是第三人称单数。","Does Amy ____ swimming?（like）||like||does后用原形。","They ____ not play football on Monday.||do||they的否定用do not。"]),
      L("现在进行时表示此刻正在发生的动作，结构是am/is/are + 动词-ing。先找be动词，再检查-ing形式。",["提示词：now、Look!、Listen!","一般加ing，去e加ing，重读闭音节双写末字母","状态动词如know、like通常不用进行时"],["Look! The bird is flying.||看！鸟正在飞。||is + flying","We are making a model now.||我们正在制作模型。||make去e加ing","I am sitting by the window.||我正坐在窗边。||sit双写t加ing"],["Listen! She ____ an English song.（sing）||is singing||动作正在发生。","They are ____ football now.（play）||playing||play直接加ing。","make的-ing形式是什么？||making||去掉末尾e再加ing。"]),
      L("一般过去时表示过去已经发生并结束的动作。规则动词加-ed，不规则动词要单独记忆；出现did后，实义动词恢复原形。",["提示词：yesterday、last week、ago","否定：did not + 动词原形","疑问：Did + 主语 + 动词原形"],["We visited the museum yesterday.||我们昨天参观了博物馆。||visit加ed","She went home at five.||她五点回家了。||go的不规则过去式went","Did you see the film?||你看那部电影了吗？||did后see用原形"],["go的过去式是什么？||went||不规则变化。","Did he ____ breakfast?（have）||have||did后用原形。","They ____ basketball last Sunday.（play）||played||last Sunday提示过去时。"]),
      L("一般将来时表示还没有发生的计划或预测。will + 动词原形强调将来或临时决定；be going to + 动词原形常表示已有计划。",["提示词：tomorrow、next week、soon","will后永远用动词原形","be going to中的be要随主语变化"],["I will call you tomorrow.||我明天会给你打电话。||will + call","We are going to visit Fuzhou.||我们打算游览福州。||已有计划","It will be sunny.||天气将会晴朗。||对未来的预测"],["She ____ visit her grandma tomorrow.||will||tomorrow提示将来。","They are going to ____ a picnic.（have）||have||to后用原形。","I ____ going to read tonight.||am||主语I配am。"]),
      L("混合时态题先圈时间词，再判断动作发生的时间，最后选择正确结构。不能看到熟悉的动词就直接选择。",["every day→一般现在时","now→现在进行时","yesterday→过去时；tomorrow→将来时"],["He plays football every Friday.||他每周五踢足球。||习惯","He is playing football now.||他现在正在踢足球。||正在发生","He played football yesterday.||他昨天踢了足球。||已经结束"],["Look! Tom ____ in the pool.（swim）||is swimming||Look提示正在发生。","Tom ____ in the pool every summer.（swim）||swims||every summer表示习惯。","Tom ____ in the pool tomorrow.（swim）||will swim||tomorrow表示将来。"])
    ],
    [
      L("主语决定谓语动词形式。先找到真正的主语，不要被主语后面的其他名词干扰。",["I/you/we/they后用动词原形","he/she/it和单数名词后用三单形式","and连接两个主语通常视为复数"],["My friends play basketball.||我的朋友们打篮球。||friends是复数","The boy with two dogs walks fast.||带着两只狗的男孩走得很快。||主语是boy","Amy and Sally like music.||艾米和莎莉喜欢音乐。||两个主语用原形"],["The girls ____ English.（study）||study||girls是复数。","My brother ____ early.（get up）||gets up||brother是单数第三人称。","Tom and Ben ____ good friends.||are||两个人作主语。"]),
      L("第三人称单数变化不仅是加s，还要观察词尾。does或doesn't出现后，后面的动词必须恢复原形。",["一般加s：reads","s/x/ch/sh/o结尾常加es：watches、goes","辅音+y变ies：studies"],["She teaches English.||她教英语。||teach加es","He studies hard.||他努力学习。||study变studies","Does she go by bus?||她坐公交车去吗？||does后go用原形"],["watch的三单形式是什么？||watches||ch结尾加es。","study的三单形式是什么？||studies||辅音+y变ies。","Does he ____ to school?（walk）||walk||does后用原形。"]),
      L("can、must、should、may等情态动词后接动词原形，没有人称和数量变化。",["can表示能力或许可","must表示必须","should表示应该、建议"],["She can swim well.||她游泳游得很好。||can后swim原形","You must finish your homework.||你必须完成作业。||must后finish原形","We should help others.||我们应该帮助别人。||should后help原形"],["He can ____ English.（speak）||speak||can后用原形。","You should ____ more water.（drink）||drink||should后用原形。","She must ____ home now.（go）||go||must后用原形。"]),
      L("不同动词后面接to do或doing，这是固定搭配，需要放在句子中记。",["want/hope/need + to do","like/enjoy + doing","let/make + 人 + 动词原形"],["I want to be a doctor.||我想成为一名医生。||want to do","She enjoys reading.||她喜欢阅读。||enjoy doing","Let me help you.||让我帮助你。||let后用原形"],["Would you like ____ with us?（come）||to come||would like to do。","Tom enjoys ____ pictures.（draw）||drawing||enjoy doing。","Let him ____ a try.（have）||have||let后用原形。"]),
      L("词形综合题要同时检查时间、主语和动词搭配。三步缺一不可。",["先圈时间词确定时态","再圈主语确定人称","最后看前一个动词或情态动词"],["She often goes running.||她经常去跑步。||often+三单；go doing","They are doing homework now.||他们现在正在做作业。||are doing","He didn't watch TV yesterday.||他昨天没看电视。||didn't后用原形"],["Amy often ____ shopping.（go）||goes||Amy三单，go shopping固定搭配。","They are ____ a kite now.（fly）||flying||are后用ing。","He didn't ____ the book.（read）||read||didn't后用原形。"])
    ],
    [
      L("时间介词要看时间范围：at用于具体时刻，on用于具体某一天，in用于较长时间和一天中的某个时段。",["at 7:00 / at noon","on Monday / on May 1st","in 2026 / in summer / in the morning"],["We meet at eight.||我们八点见。||具体时刻用at","The test is on Friday.||考试在星期五。||具体某天用on","I was born in 2014.||我出生于2014年。||年份用in"],["____ Sunday morning||on||具体到星期日早上。","____ 6:30||at||具体时刻。","____ winter||in||季节用in。"]),
      L("地点介词要在脑中画图：in在内部，on在表面，at强调地点点位；方位词要看物体之间的位置关系。",["in the box / on the desk / at school","between在两者之间；among在三者及以上之间","across穿过表面；through穿过内部"],["The ball is under the chair.||球在椅子下面。||under表示正下方","The bank is between the school and the park.||银行在学校和公园之间。||两者之间","Walk across the street.||穿过街道。||从街道表面横过"],["The cat is ____ the box.（在里面）||in||表示内部。","The library is ____ the bank and the hospital.||between||两个地点之间。","Go ____ the tunnel.||through||从隧道内部穿过。"]),
      L("for、from、with、by含义很多，要结合完整搭配。不要只背一个中文意思。",["for表示为了或持续时间","from表示来自或起点","with表示和、带有；by表示方式或在旁边"],["This gift is for you.||这份礼物是给你的。||对象","I'm from Putian.||我来自莆田。||来源","We go to school by bus.||我们乘公交上学。||交通方式"],["She is ____ Fuzhou.||from||表示来自哪里。","I write ____ a pen.||with||表示使用具体工具。","We travel ____ train.||by||by+交通工具。"]),
      L("固定搭配要按词组整体记忆，并放进真实句子。一个词搭配不同介词，意思可能改变。",["look at看；look for寻找；look after照顾","be good at擅长；be afraid of害怕","take photos拍照；go swimming去游泳"],["Please look at the map.||请看地图。||look at","I'm looking for my key.||我正在找钥匙。||look for","She is good at English.||她擅长英语。||be good at"],["Please look ____ the baby.（照顾）||after||look after表示照顾。","He is good ____ playing chess.||at||be good at doing。","Let's go ____.（游泳）||swimming||go swimming固定搭配。"]),
      L("介词错题要把介词和它前后的词一起抄成短语，而不是只抄一个介词。",["记录完整搭配","用地点图或时间轴解释","换一个新情境再造句"],["on the wall / in the wall||在墙表面 / 在墙内部||位置不同介词不同","arrive in Fuzhou / arrive at school||到达福州 / 到达学校||大地点in，小地点at","for two hours||持续两小时||for+一段时间"],["arrive ____ Beijing||in||大地点用arrive in。","There is a window ____ the wall.||in||窗户嵌在墙里面。","I studied ____ two hours.||for||for表示持续时间。"])
    ],
    [
      L("形容词描述名词或放在be、look、feel等系动词后；副词通常描述动作怎样发生。",["a careful student：形容词修饰名词","She is careful：形容词作表语","She writes carefully：副词修饰writes"],["The music is beautiful.||音乐很美。||beautiful在be后描述music","He runs quickly.||他跑得快。||quickly修饰runs","This is an easy question.||这是一道容易的题。||easy修饰question"],["She sings ____.（beautiful）||beautifully||修饰动作sings用副词。","The soup smells ____.（good）||good||smell是系动词，后接形容词。","He is a ____ driver.（careful）||careful||修饰名词driver。"]),
      L("比较级用于两者比较，最高级用于三者或以上。看到than通常想到比较级，看到of/in范围常想到最高级。",["一般加-er/-est","以e结尾加-r/-st","重读闭音节双写末字母再加-er/-est"],["tall—taller—tallest||高的||一般直接加词尾","nice—nicer—nicest||友好的||以e结尾","big—bigger—biggest||大的||双写g"],["small的比较级是什么？||smaller||直接加er。","large的最高级是什么？||largest||以e结尾加st。","hot的比较级是什么？||hotter||双写t加er。"]),
      L("不规则比较形式必须单独记。多音节形容词通常用more和most。",["good/well—better—best","bad—worse—worst","many/much—more—most"],["This book is more interesting than that one.||这本书比那本更有趣。||多音节用more","Today is better than yesterday.||今天比昨天好。||good的不规则形式","He has the most books.||他的书最多。||many的最高级"],["good的比较级是什么？||better||不规则变化。","beautiful的比较级是什么？||more beautiful||多音节词前加more。","bad的最高级是什么？||worst||不规则变化。"]),
      L("as...as表示“和……一样”，中间用形容词或副词原级；not as...as表示“不如”。",["as tall as","as carefully as","not as fast as"],["Amy is as tall as Lily.||艾米和莉莉一样高。||中间用原级tall","Tom doesn't run as fast as Ben.||汤姆跑得不如本快。||not as...as","Please speak as clearly as you can.||请尽量说清楚。||副词clearly"],["She is as ____ as her sister.（kind）||kind||as...as中用原级。","This bag is not as ____ as that one.（heavy）||heavy||不能用heavier。","He works as ____ as Tom.（careful）||carefully||修饰works用副词。"]),
      L("比较题要先确认比较对象是否同类，再判断两者还是三者以上，最后检查词形。",["两者→比较级+than","三者以上→the+最高级","避免把人和人的某一部分直接比较"],["My room is bigger than yours.||我的房间比你的大。||yours=my room对应同类","She is the tallest in her class.||她是班上最高的。||班级范围内最高","The weather in Putian is warmer than that in Beijing.||莆田的天气比北京暖。||that代替weather"],["Of the three, Jack is the ____.（young）||youngest||三者比较用最高级。","My bike is newer than ____.（你的自行车）||yours||yours代替your bike。","Which is ____, a tiger or a lion?（strong）||stronger||两者比较。"])
    ],
    [
      L("英语陈述句最基本的主干是“主语+谓语”，有些动词后还需要宾语。先找谁，再找做什么。",["主语说明谁或什么","谓语表示动作或状态","时间、地点通常放在主干之后"],["The boy reads books every evening.||男孩每天晚上读书。||boy主语，reads谓语，books宾语","My sister is happy.||我妹妹很开心。||is连接主语和状态","We play football in the park.||我们在公园踢足球。||地点放在后面"],["找出句子主语：The little dog runs fast.||The little dog||整个名词短语作主语。","找出谓语：Amy likes music.||likes||表示主语的动作。","排列：every day / I / English / study||I study English every day.||主干在前，时间在后。"]),
      L("一般疑问句要把be动词、助动词或情态动词移到主语前。实义动词句需要do/does/did帮助。",["Are you...?","Does she + 动词原形...?","Can he + 动词原形...?"],["Is he at home?||他在家吗？||be动词提前","Do they like apples?||他们喜欢苹果吗？||they配do","Did she go yesterday?||她昨天去了吗？||did后go原形"],["改为疑问句：She is a teacher.||Is she a teacher?||is提前。","改为疑问句：Tom plays football.||Does Tom play football?||三单用does，plays恢复原形。","改为疑问句：They went home.||Did they go home?||过去时用did。"]),
      L("特殊疑问句通常是“疑问词+一般疑问句语序”。先选择疑问词，再完成后面的倒装结构。",["who问人；what问事物","when问时间；where问地点","why问原因；how问方式或状态"],["Where do you live?||你住在哪里？||where+do+主语+原形","When did he arrive?||他什么时候到的？||过去时用did","Why are you late?||你为什么迟到？||be动词提前"],["____ do you go to school? By bus.||How||回答是方式。","Where ____ she live?||does||主语she，一般现在时。","When did they ____?（leave）||leave||did后用原形。"]),
      L("频率副词通常放在实义动词前、be动词和情态动词后。地点通常在时间前。",["I often read.","She is always kind.","We play in the park after school."],["He usually gets up early.||他通常早起。||usually在实义动词前","They are never late.||他们从不迟到。||never在be后","I met him at school yesterday.||我昨天在学校遇见他。||地点在时间前"],["排列：often / she / walks / to school||She often walks to school.||频率副词在实义动词前。","排列：always / is / he / helpful||He is always helpful.||频率副词在be后。","排列：yesterday / in the library / studied / we||We studied in the library yesterday.||地点在时间前。"]),
      L("连词成句先找带大写字母的起点和标点，再找主干，最后添加修饰语。改错题一次只检查一个项目。",["第一遍查主谓","第二遍查时态和词形","第三遍查语序、大小写和标点"],["What did you do yesterday?||你昨天做了什么？||疑问词+did+主语+原形","There are two books on the desk.||桌上有两本书。||there be与最近名词一致","She doesn't like coffee.||她不喜欢咖啡。||doesn't后like原形"],["改错：Does she likes music?||Does she like music?||does后动词用原形。","改错：Where you are going?||Where are you going?||be动词要移到主语前。","连词：books / there / three / are / bag / the / in||There are three books in the bag.||先搭there are主干。"])
    ],
    [
      L("and连接相同方向的信息，but连接转折，or表示选择或否定句中的“也不”。连接词前后要是语法完整且逻辑匹配的信息。",["and：而且、然后","but：但是","or：或者，否则"],["I like apples and bananas.||我喜欢苹果和香蕉。||并列","He is young but careful.||他年轻但是很细心。||转折","Hurry up, or you'll be late.||快点，否则你会迟到。||结果警告"],["I was tired, ____ I finished my homework.||but||前后是转折。","Would you like tea ____ juice?||or||表示选择。","She opened the book ____ began to read.||and||动作顺接。"]),
      L("because说明原因，so说明结果。小学阶段通常不要在同一个英文句子中同时使用because和so。",["结果 + because + 原因","原因，so + 结果","根据问题why选择because回答"],["I stayed home because it rained.||因为下雨，我待在家。||because引出原因","It rained, so I stayed home.||下雨了，所以我待在家。||so引出结果","Why are you happy? Because I won.||你为什么开心？因为我赢了。||回答原因"],["I was late ____ the bus was slow.||because||后面说明原因。","The bus was slow, ____ I was late.||so||后面说明结果。","改错：Because it rained, so we stayed home.||Because it rained, we stayed home.||because和so不同时使用。"]),
      L("if表示“如果”，when表示“当……时候”。主句说将来时，if/when引导的时间或条件部分常用一般现在时表达将来。",["If it rains, we will stay home.","When he comes, I will tell him.","主将从现是初中衔接重点"],["If you study hard, you will improve.||如果努力学习，你会进步。||条件","When I get home, I will call you.||我到家时会给你打电话。||时间","If she is free, she can come.||如果她有空，她可以来。||if从句用现在时"],["If it ____ tomorrow, we will cancel the trip.（rain）||rains||if从句用一般现在时。","When he ____ back, I will tell him.（come）||comes||when从句用一般现在时。","____ you need help, call me.||If||表示条件。"]),
      L("who、which、that等可以把补充信息接在名词后。入门阶段先找先行词，再判断从句说明的是谁或什么。",["who通常指人","which通常指物","从句内部用陈述语序"],["The girl who is singing is Amy.||正在唱歌的女孩是艾米。||who说明girl","This is the book that I like.||这是我喜欢的书。||that说明book","I know where he lives.||我知道他住在哪里。||从句用he lives陈述语序"],["The boy ____ helps me is Tom.||who||先行词boy指人。","This is the bike ____ I bought.||that||先行词bike指物。","改错：I know where does he live.||I know where he lives.||从句用陈述语序。"]),
      L("长句阅读先按连接词切分，再分别找每个部分的主语和谓语，最后合并意思。",["圈and/but/because/if/when","给每个分句画主谓线","判断分句之间是并列、转折、因果还是条件"],["I stayed home because I was ill, but I finished my work.||我因病待在家，但完成了工作。||because原因，but转折","If it is sunny, we will go out and play football.||如果晴天，我们会出去踢球。||if条件，and并列动作","When I arrived, Amy was reading.||我到达时，艾米正在阅读。||when连接两个时间相关动作"],["句中but表示什么关系？||转折||前后信息方向不同。","If you are tired, you should ____.||rest||条件满足时给出建议。","翻译：因为下雨，所以我们没有出去。||We didn't go out because it rained.||用because连接结果和原因。"])
    ],
    [
      L("阅读前先看标题、图片和首句，预测文章可能讲什么。预测不是猜答案，而是帮助大脑准备相关词汇。",["圈标题关键词","读每段首句","带着‘谁、何时、何地、做什么’进入文章"],["My Busy Sunday||我忙碌的星期日||可能按时间写一天活动","A Visit to Meizhou Island||湄洲岛之旅||可能写地点和旅行经历","How to Keep Healthy||如何保持健康||可能提出建议"],["标题“A School Trip”最可能写什么？||一次学校旅行||school trip是学校组织的旅行。","看到How to...标题，应重点寻找什么？||方法或步骤||How to表示如何做。","首句通常能帮助判断什么？||主题||很多短文首句概括主要内容。"]),
      L("人物较多时，在代词旁写出它指代的人。判断he、she、they、it不能只看最近的名词，还要看句意。",["圈所有人名","在代词旁写指代对象","用动作和身份验证"],["Amy met Lily. She gave Lily a book.||艾米遇到莉莉。她给莉莉一本书。||She指Amy","The boys saw a dog. It was hungry.||男孩们看见一只狗，它饿了。||It指dog","Tom and Ben went home. They were tired.||汤姆和本回家了，他们累了。||They指两个人"],["Lucy called Kate because she needed help. 若后文说Kate came to help，she最可能指谁？||Lucy||Lucy需要帮助，Kate前来帮助。","The cat saw the bird, but it flew away. it指什么？||the bird||会飞走的是鸟。","Mike and I are classmates. We...中的We指谁？||Mike and I||we包含说话者。"]),
      L("事件排序要圈时间词和动作。先后顺序可能由first、then、after、before、finally或动词时态表示。",["给时间词编号","把动作写成简短中文","检查前因后果是否合理"],["First we bought tickets. Then we entered the museum.||先买票，然后进博物馆。||明确顺序","After lunch, we climbed the hill.||午饭后我们爬山。||after提示后发生","Before bed, I read a story.||睡觉前我读故事。||before提示先发生"],["First之后常接哪类信息？||第一个动作||表示顺序起点。","We ate dinner before we watched TV. 哪件事先发生？||ate dinner||before连接先后。","finally表示什么？||最后||通常引出最后一步或结果。"]),
      L("猜生词不要求知道词典里的全部意思，只要根据上下文判断它在当前句中的大概含义。",["看同义解释或举例","看转折词前后的对比","拆词根、前缀或熟悉部分"],["The road was narrow, so only one car could pass.||道路很窄，所以只能过一辆车。||由结果猜narrow=窄的","Unlike his noisy brother, Tom is quiet.||不像吵闹的哥哥，Tom很安静。||unlike和对比帮助猜词","reusable bags can be used again||可重复使用的袋子可以再次使用||re+use帮助理解"],["“She was exhausted, so she went to bed at once.” exhausted最可能是？||非常疲倦的||马上睡觉是线索。","“The glass is fragile. Be careful.” fragile最可能是？||易碎的||be careful提示。","unhappy中的un-通常表示什么？||否定||happy前加un变不开心。"]),
      L("限时阅读不是读得越快越好，而是先看题、带关键词回原文定位。每道答案都要能指出证据句。",["先读问题并圈关键词","回原文定位同义表达","排除与原文矛盾、无依据或偷换对象的选项"],["Question: Why did Ben stay home? Evidence: Because he had a cold.||本为什么待在家？因为感冒。||直接原因证据","Question: When did they leave? Evidence: At half past eight.||他们何时离开？八点半。||时间证据","Question: How did Amy feel? Evidence: She smiled all day.||艾米感觉如何？她整天微笑。||由行为推断开心"],["原文说Tom walked to school，选项“by bus”为什么错？||交通方式与原文矛盾||必须依据原文。","问题含Why，应重点找什么词？||because或原因表达||帮助定位原因。","推断题可以完全凭生活常识吗？||不可以||推断也必须有文章证据。"])
    ],
    [
      L("完形填空先通读全文，了解人物、时间和主题，再逐空判断需要什么词性。不要从第一空开始盲选。",["空前冠词后常需要名词","be动词后常需要形容词或-ing","情态动词后用动词原形"],["a ____ student → careful||一名细心的学生||名词前需要形容词","is ____ a book → reading||正在读书||be+doing","can ____ well → swim||能游得好||can后原形"],["She is a ____ girl.（kind/kindly）||kind||名词girl前用形容词。","He runs ____.（quick/quickly）||quickly||修饰runs用副词。","They can ____ English.（speak/speaks）||speak||can后原形。"]),
      L("上下文中的时间词决定时态，代词帮助确认人物。做空格前后至少各读一句。",["yesterday/last→过去时","now/Look→进行时","every/often→一般现在时"],["Yesterday we went to the zoo. We saw pandas there.||昨天去动物园并看熊猫。||went和saw时态一致","Look! Amy is running. She is very fast.||看！艾米正在跑。||She指Amy","Tom often reads, so he knows many stories.||Tom常阅读，因此知道许多故事。||often提示一般现在时"],["Last Sunday, we ____ a picnic.（have）||had||last Sunday提示过去时。","Listen! Someone ____ at the door.（knock）||is knocking||Listen提示正在发生。","Lily likes music. ____ plays the piano.||She||代替Lily。"]),
      L("近义词、近形词不能靠眼熟选择。先说出每个选项的中文，再比较它和句子的搭配。",["borrow借入；lend借出","say说内容；tell告诉某人；speak说语言","look看；see看见；watch观看"],["Can I borrow your pen?||我能借你的笔吗？||从别人那里借入","Please tell me the answer.||请告诉我答案。||tell+人","We watch TV at night.||我们晚上看电视。||观看节目"],["Please ____ me your name.（say/tell）||tell||tell somebody。","May I ____ your book?（borrow/lend）||borrow||我从你那里借入。","He can ____ English.（say/speak）||speak||speak+语言。"]),
      L("答案填回全文后要检查逻辑：人物是否一致、前后是否矛盾、连接词是否正确、时态是否统一。",["读完整句而不是只读空格","读前后两句检查因果","最后快速通读全文"],["It was raining, so we stayed inside.||下雨了，所以待在室内。||因果合理","He was tired, but he kept working.||他累了，但继续工作。||转折合理","First wash the fruit. Then cut it.||先洗水果，再切。||顺序合理"],["It was cold, ____ I wore a coat.||so||寒冷导致穿外套。","He is young, ____ he knows a lot.||but||年龄小与懂得多形成转折。","____, we arrived at the top.（最后）||Finally||引出最后结果。"]),
      L("做完完形后把错误归到词性、时态、搭配、逻辑四类，再针对同类题补练。",["词性错：标注名/动/形/副","时态错：补圈时间词","搭配错：记录完整词组；逻辑错：写前后关系"],["interested / interesting||感兴趣的 / 令人感兴趣的||描述对象不同","went / gone||过去式 / 过去分词||结构不同","because / so||因为 / 所以||连接方向不同"],["I am ____ in science.（interested/interesting）||interested||人感到兴趣。","The film is ____.（interested/interesting）||interesting||电影令人感兴趣。","He has ____ to Beijing.（went/gone）||gone||has后用过去分词。"])
    ],
    [
      L("五句法帮助写完整段落：人物、时间、地点、事情、感受。先保证每句正确，再增加细节。",["第1句点明主题","中间3句按顺序写事情","最后1句表达感受或收获"],["Last Sunday, I went to the park with my family.||上周日我和家人去了公园。||时间+人物+地点","We flew kites and took photos.||我们放风筝并拍照。||具体活动","We were tired but happy.||我们累但是开心。||结尾感受"],["写旅行开头应包含哪三类信息？||时间、人物、地点||帮助读者迅速理解情境。","“We happy.”如何改正？||We were happy.||形容词前需要be动词，过去经历用were。","连接两个并列动作可用什么词？||and||如played and sang。"]),
      L("first、then、next、after that、finally能让文章顺序清楚。连接词后仍要写完整句子。",["First引出第一步","Then/Next推进过程","Finally给出最后一步或结果"],["First, we made a plan.||首先我们制定计划。||起点","Then, we bought the tickets.||然后我们买票。||过程","Finally, we arrived home safely.||最后我们安全到家。||结尾"],["表示“接着”可用什么词？||Then||也可用Next。","Finally通常放在文章什么位置？||最后一步或结果前||帮助结束叙述。","改错：Then went to the museum.||Then we went to the museum.||连接词后仍需主语。"]),
      L("写过去经历要用一般过去时；写未来计划要用will或be going to。整篇时态要与主题一致。",["过去经历：was/were、went、saw、had","未来计划：will + 原形","be going to + 原形表示已有安排"],["We visited Xiamen last summer.||去年夏天我们游览了厦门。||过去经历","I will read more books this summer.||今年夏天我会读更多书。||未来计划","We are going to take a train.||我们打算坐火车。||已有安排"],["Last year I ____ to Fuzhou.（go）||went||过去时间用went。","Next week we will ____ a museum.（visit）||visit||will后原形。","She is going to ____ English.（study）||study||to后用原形。"]),
      L("写完必须按固定顺序检查：句首大写、标点、单词拼写、主谓一致、时态。朗读能发现漏词。",["逐句指读，不跳读","圈出所有动词检查形式","检查专有名词和I是否大写"],["My friend Amy lives in Putian.||我的朋友Amy住在莆田。||人名地点大写","She likes reading books.||她喜欢读书。||likes与she一致","Yesterday, we had a good time.||昨天我们玩得很开心。||had过去式"],["改错：i live in putian.||I live in Putian.||I和地名首字母大写。","改错：She like music.||She likes music.||she后动词用三单。","句末最常漏掉什么？||标点||陈述句通常用句号。"]),
      L("限时写作先用3分钟列提纲，12分钟写，5分钟检查。录音复述时不要逐字背，按关键词表达。",["提纲只写关键词","每句表达一个主要信息","录音后检查停顿、发音和完整性"],["Topic: My Summer Plan||主题：我的暑假计划||列出where/what/with whom","I am going to learn swimming.||我打算学习游泳。||具体计划","I think it will be exciting.||我认为会很令人兴奋。||结尾期待"],["写作前列提纲的目的是什么？||组织内容并避免漏写||不是浪费时间。","复述时忘记原句怎么办？||用自己会的词表达同一意思||交流重在清楚。","60—80词短文至少应有什么？||清楚的开头、过程和结尾||结构完整比堆难词重要。"])
    ],
    [
      L("模拟卷A要按真实考试限时完成。不会的题先做标记，不要在一道题上停留太久。",["先易后难","犹豫题做星号","最后预留5分钟检查答题完整性"],["词汇题约10分钟||控制节奏||先拿稳基础分","语法和语境题约15分钟||读完整句||不凭眼熟","阅读和写作约25分钟||找证据并检查||保留输出时间"],["一道题思考很久仍不会时怎么办？||先标记并继续||避免影响后面会做的题。","交卷前首先检查什么？||是否漏题||漏题一定失分。","模拟时可以边查答案吗？||不可以||先真实检测，再统一订正。"]),
      L("统计失分要按能力分类，不只写题号。相同错误出现两次，就说明对应知识点需要回炉。",["词汇：词义、拼写、近形词","语法：时态、词形、搭配、语序","阅读写作：定位、理解、表达"],["错题：Does he likes...?||动词词形||does后原形","错题：How many milk...?||名词数量||milk不可数用much","阅读选项与原文人物不符||证据定位||返回原文核对对象"],["把“went写成go”归到哪类？||时态||过去时间下动词形式错误。","把there看成three归到哪类？||近形词||拼写识别错误。","阅读凭常识选错归到哪类？||证据定位||答案必须来自文章。"]),
      L("回炉不是重看所有内容，而是根据错因跳回对应模块，重新学规则、做3道同类题，再口头解释。",["错因对应知识模块","先学会解释规则","隔一天再做原错题"],["many/much错→名词数量模块||精准补漏||不重学无关内容","went/go错→时态模块||画时间线||用三个时间造句","语序错→句子结构模块||找主谓||重新排列"],["补漏后怎样判断真正学会？||能独立做同类新题并解释原因||记住答案不等于掌握。","错题是否要立即连续做很多遍？||不需要||订正后隔一段时间再测更有效。","只抄正确答案有用吗？||作用很小||还要说明错因和规则。"]),
      L("模拟卷B用于检查补漏是否有效，应与A卷题型相似但内容不同。对比两次错误类别比只看总分更重要。",["同类错误减少才算进步","新错误也要归类","稳定达到80%左右再进入最终整理"],["A卷18/30，B卷24/30||正确率明显提升||检查是否靠理解","两卷都错介词||专项仍薄弱||回到第5周","B卷出现新阅读错误||新增薄弱点||补证据定位"],["两次分数相同就代表没有进步吗？||不一定||还要比较错误类型和题目难度。","同一类题连续错应怎么做？||返回对应模块重新学习||不能只继续刷卷。","模拟卷的主要作用是什么？||发现并验证薄弱点||不是为了收集分数。"]),
      L("最后清单要短而有用：20个最易错词、10个核心句型、5条个人语法提醒。每一条都来自真实错题。",["易错词写英文、中文和例句","句型保留可替换位置","语法提醒用自己的话写"],["weather / whether||天气 / 是否||近形词清单","Does he like...?||他喜欢……吗？||does后原形","看到yesterday先检查过去式||个人提醒||来自时态错题"],["最终词表为什么只选20个？||集中解决最常错的词||清单过长难以反复复习。","句型清单应该只有中文吗？||不应该||要有英文结构和自己的例句。","完成12周后还需要复习吗？||需要||按第1、3、7天间隔回顾最终清单。"])
    ]
  ];
})();
