/* 原创课程资料：按闽教版主题组织，不复制教材课文。 */
(() => {
  "use strict";

  const parseWords = (text) => text.split(",").map((item, index) => {
    const [word, meaning] = item.split(":");
    const starters = ["I can say", "Look at", "This is", "I know", "We use"];
    return { word, meaning, example: `${starters[index % starters.length]} “${word}”.`, exampleZh: `我能在本单元情境中正确使用“${meaning}”。` };
  });
  const parsePatterns = (items) => items.map((item) => {
    const [en, zh, rule] = item.split("|");
    return { en, zh, rule };
  });
  const makeUnit = (title, zh, icon, goal, words, patterns, story) => ({
    title, zh, icon, goal, core: parseWords(words), patterns: parsePatterns(patterns), story
  });

  const U = {
    meeting: makeUnit("Meeting Friends", "认识新朋友", "👋", "能礼貌问候、介绍自己并关心朋友。", "hello:你好,name:名字,friend:朋友,meet:遇见,please:请,fine:很好,goodbye:再见,day:一天", ["Hello! I'm Amy.|你好！我是艾米。|I'm 是 I am 的缩写，用来介绍自己。","What's your name?|你叫什么名字？|what's 是 what is 的缩写。","How are you? — I'm fine.|你好吗？—我很好。|问候后要记得回应和致谢。"], "Amy meets Ben at the school gate. They say hello and tell each other their names. Now they are new friends."),
    numbers: makeUnit("Fun Numbers", "有趣的数字", "🔢", "能认读数字，并用数字询问数量、年龄和电话号码。", "one:一,two:二,three:三,four:四,five:五,six:六,seven:七,eight:八,nine:九,ten:十", ["How many ducks?|有多少只鸭子？|how many 后接可数名词复数。","How old are you? — I'm nine.|你几岁？—我九岁。|回答年龄用 I'm + 数字。","What's your phone number?|你的电话号码是多少？|电话号码通常逐个数字读。"], "There are five ducks by the river. Ben is nine years old. He counts the ducks from one to five."),
    colors: makeUnit("Colors Around Us", "身边的颜色", "🌈", "能辨认颜色并描述一个或多个物品的颜色。", "red:红色,blue:蓝色,green:绿色,yellow:黄色,black:黑色,white:白色,pink:粉色,orange:橙色,color:颜色,colorful:五颜六色的", ["What color is it? — It's green.|它是什么颜色？—绿色。|单个物品用 it。","What color are they? — They're red.|它们是什么颜色？—红色。|多个物品用 they。","Show me blue, please.|请给我看蓝色。|祈使句用动词原形开头。"], "Our classroom is colorful. The door is blue, the flowers are red and the little clock is yellow."),
    family: makeUnit("Loving My Family", "我爱我的家", "🏠", "能介绍家庭成员，并用who询问人物。", "family:家庭,father:爸爸,mother:妈妈,brother:兄弟,sister:姐妹,grandpa:爷爷或外公,grandma:奶奶或外婆,love:爱,he:他,she:她", ["This is my mother.|这是我的妈妈。|介绍身边的人用 This is...","Who is he? — He's my brother.|他是谁？—他是我哥哥。|问男性用 he，回答可用 He's。","Who are they? — They're my grandparents.|他们是谁？—他们是我的祖父母。|多人用 they/are。"], "Mia has a warm family. Her father likes reading and her mother likes music. They have dinner together every day."),
    animals: makeUnit("Our Animal Friends", "动物朋友", "🐼", "能说出常见动物、描述特征并表达喜爱。", "bear:熊,panda:熊猫,monkey:猴子,tiger:老虎,rabbit:兔子,elephant:大象,big:大的,small:小的,cute:可爱的,friend:朋友", ["What's this? — It's a bear.|这是什么？—它是一只熊。|不确定的单数动物用 a/an。","I like pandas.|我喜欢熊猫。|表示一类动物时常用复数。","It has a long nose.|它有一个长鼻子。|第三人称单数用 has。"], "The panda is black and white. It is big, but it looks cute. Many children like this quiet animal."),
    clothes: makeUnit("Clothes and Weather", "衣物与天气", "🧥", "能认读衣物，根据天气选择合适穿着。", "shirt:衬衫,sweater:毛衣,coat:外套,skirt:裙子,shoes:鞋子,hat:帽子,warm:温暖的,cold:寒冷的,wear:穿,weather:天气", ["Where is my sweater?|我的毛衣在哪里？|where 用来询问地点。","It's cold today.|今天很冷。|描述天气可用 It's + 形容词。","Put on your coat.|穿上你的外套。|put on 强调穿的动作。"], "It is cold in the morning. Lily puts on her yellow sweater and blue coat before she goes outside."),
    food: makeUnit("Food We Like", "喜欢的食物", "🍜", "能说出食物名称，表达喜欢与礼貌点餐。", "rice:米饭,noodles:面条,bread:面包,milk:牛奶,egg:鸡蛋,fish:鱼肉,vegetable:蔬菜,hungry:饥饿的,like:喜欢,want:想要", ["I like noodles.|我喜欢面条。|like 后可接名词。","What would you like?|你想要什么？|would like 比 want 更礼貌。","I'd like some rice.|我想要一些米饭。|I'd like 是 I would like 的缩写。"], "Ben is hungry after school. He would like some noodles, an egg and a glass of milk."),
    happy: makeUnit("Happy Days", "快乐的日子", "🎈", "能谈论日期、生日和节日活动。", "birthday:生日,party:聚会,gift:礼物,cake:蛋糕,happy:快乐的,today:今天,tomorrow:明天,sing:唱歌,dance:跳舞,wish:祝愿", ["When is your birthday?|你的生日是什么时候？|when 用来询问时间。","Happy birthday to you!|祝你生日快乐！|祝福语后可回应 Thank you。","Let's sing together.|让我们一起唱歌。|Let's 后接动词原形。"], "Today is May's birthday. Her friends bring a small gift. They sing, play and share a cake together."),
    school: makeUnit("Our School", "我们的学校", "🏫", "能介绍学校场所、班级和校园活动。", "school:学校,classroom:教室,library:图书馆,playground:操场,computer room:电脑室,class:班级,blackboard:黑板,read:阅读,play:玩,there:那里", ["Where is the library?|图书馆在哪里？|where 询问地点。","We can read books there.|我们可以在那里读书。|can 后接动词原形。","Which class are you in?|你在哪个班？|which 用来从一定范围中选择。"], "Our school is not big, but it is beautiful. We read in the library and play sports on the playground."),
    daily: makeUnit("Daily Life", "日常生活", "⏰", "能按时间描述自己和他人的日常安排。", "get up:起床,breakfast:早餐,go to school:上学,lunch:午餐,homework:作业,dinner:晚餐,go to bed:睡觉,often:经常,early:早地,clock:时钟", ["I get up at 7:00.|我七点起床。|具体时刻前用 at。","She has breakfast at 7:30.|她七点半吃早餐。|she 后动词常加-s或用has。","What time do you go to bed?|你几点睡觉？|what time 询问具体时刻。"], "Lily gets up early. She has breakfast at seven and walks to school with her brother."),
    hobbies: makeUnit("Our Hobbies", "我们的爱好", "🎨", "能询问和介绍爱好，并说明喜欢做什么。", "hobby:爱好,draw:画画,read:阅读,swim:游泳,sing:唱歌,dance:跳舞,play chess:下棋,take photos:拍照,collect:收集,interesting:有趣的", ["What's your hobby?|你的爱好是什么？|hobby 是可数名词。","I like drawing.|我喜欢画画。|like doing 表示喜欢做某事。","What does she like doing?|她喜欢做什么？|she 作主语时问句借助 does。"], "Tom likes taking photos. He takes pictures of flowers, birds and smiling faces in the park."),
    festivals: makeUnit("Chinese Festivals", "中国节日", "🏮", "能介绍中国传统节日、食物和活动。", "festival:节日,Spring Festival:春节,Mid-Autumn Festival:中秋节,lantern:灯笼,dumpling:饺子,mooncake:月饼,dinner:晚餐,together:一起,visit:拜访,celebrate:庆祝", ["The Spring Festival is coming.|春节快到了。|be coming 可表示即将到来。","We have dinner together.|我们一起吃晚餐。|together 常放在句末。","What do you do at the festival?|你们在节日做什么？|一般习惯用一般现在时。"], "At the Spring Festival, Mei visits her grandparents. The family makes dumplings and has a big dinner together."),
    classroom: makeUnit("Our Classroom", "我们的教室", "🪑", "能认读教室物品，描述位置并提出简单请求。", "desk:课桌,chair:椅子,window:窗户,door:门,light:灯,book:书,bag:书包,in:在里面,on:在上面,under:在下面", ["Where is the book?|书在哪里？|where 问位置。","It's on the desk.|它在课桌上。|on 表示在物体表面。","Please open the window.|请打开窗户。|please 让请求更礼貌。"], "A red book is on the desk. A blue bag is under the chair. The classroom is clean and bright."),
    animalnumbers: makeUnit("Numbers and Animals", "数字与动物", "🦁", "能数较大数量并描述动物数量。", "eleven:十一,twelve:十二,thirteen:十三,fourteen:十四,fifteen:十五,horse:马,sheep:绵羊,cow:奶牛,how many:多少,count:数数", ["How many horses are there?|有多少匹马？|there are 表示有多个。","There are twelve.|有十二匹。|复数数量用 are。","Let's count them.|我们数一数吧。|代词 them 指代多个对象。"], "There are twelve sheep and five cows on the farm. Nina counts them carefully."),
    time: makeUnit("Numbers and Time", "数字与时间", "🕒", "能正确读整点和半点，询问活动时间。", "twenty:二十,thirty:三十,forty:四十,fifty:五十,time:时间,o'clock:点钟,half:一半,late:迟到的,now:现在,begin:开始", ["What's the time?|几点了？|也可以说 What time is it?","It's half past seven.|七点半。|half past 表示某点半。","School begins at eight.|学校八点开始上课。|时刻前用 at。"], "It is half past seven now. Ken eats breakfast quickly because school begins at eight."),
    activities: makeUnit("Daily Activities", "日常活动", "🚲", "能谈论每天经常进行的活动和频率。", "walk:步行,ride:骑,run:跑步,exercise:锻炼,watch TV:看电视,clean:打扫,usually:通常,sometimes:有时,after school:放学后,busy:忙碌的", ["I usually walk to school.|我通常步行上学。|频率副词放在实义动词前。","He sometimes rides a bike.|他有时骑自行车。|he 后 ride 变 rides。","What do you do after school?|你放学后做什么？|do 在问句中帮助构成一般现在时。"], "After school, Jack usually does his homework. He sometimes rides a bike with his dad."),
    meals: makeUnit("Meals", "一日三餐", "🥗", "能谈论三餐、食物选择与健康搭配。", "breakfast:早餐,lunch:午餐,dinner:晚餐,porridge:粥,vegetable:蔬菜,fruit:水果,chicken:鸡肉,healthy:健康的,delicious:美味的,meal:一餐", ["What's for breakfast?|早餐吃什么？|What's for... 用来询问餐食。","We have bread and milk.|我们吃面包、喝牛奶。|have 可表示吃或喝。","Vegetables are healthy.|蔬菜很健康。|复数主语搭配 are。"], "For breakfast, Amy has bread, milk and an egg. She knows a good breakfast gives her energy."),
    christmas: makeUnit("Christmas", "圣诞节文化", "🎄", "能理解常见圣诞词汇并进行简单节日问候。", "Christmas:圣诞节,tree:树,card:卡片,present:礼物,star:星星,Santa:圣诞老人,Merry:愉快的,decorate:装饰,give:给予,wish:祝愿", ["Merry Christmas!|圣诞快乐！|常用节日祝福语。","Here is a present for you.|这是给你的礼物。|for 表示给某人。","Let's decorate the tree.|我们装饰圣诞树吧。|Let's 后接动词原形。"], "The children make cards and decorate a small tree. They learn that a kind wish can be a lovely present."),
    springfestival: makeUnit("The Spring Festival", "春节", "🧧", "能谈论春节准备、拜年与家庭活动。", "New Year:新年,red envelope:红包,firework:烟花,clean:打扫,wear:穿,new:新的,visit:拜访,grandparents:祖父母,Happy New Year:新年快乐,lucky:幸运的", ["What are you doing?|你正在做什么？|正在发生的动作可用 be + doing。","I'm cleaning the room.|我正在打扫房间。|I 搭配 am。","Happy New Year!|新年快乐！|回应也可说 Happy New Year!"], "Before the Spring Festival, Bo cleans his room and puts up red decorations. On New Year's Day, he visits his grandparents."),
    weekly: makeUnit("Weekly Activities", "每周活动", "📅", "能说出星期并介绍一周安排。", "Monday:星期一,Tuesday:星期二,Wednesday:星期三,Thursday:星期四,Friday:星期五,Saturday:星期六,Sunday:星期日,week:星期,club:社团,every:每个", ["What do you do on Monday?|你星期一做什么？|星期前用 on。","I have an art class.|我有一节美术课。|课程前常用 have。","She goes swimming on Sunday.|她星期日游泳。|she 后 go 变 goes。"], "Ben has a music club on Tuesday and goes swimming on Sunday. He writes the plan on his calendar."),
    weather: makeUnit("Weather", "天气", "🌦️", "能描述天气并给出活动建议。", "sunny:晴朗的,rainy:下雨的,cloudy:多云的,windy:有风的,snowy:下雪的,hot:热的,cold:冷的,umbrella:雨伞,weather:天气,outside:在外面", ["How's the weather?|天气怎么样？|也可说 What's the weather like?","It's sunny and warm.|天气晴朗又温暖。|两个形容词可用 and 连接。","Take an umbrella with you.|随身带把伞。|take...with you 表示随身带。"], "It is cloudy in the morning and rainy in the afternoon. Mia takes an umbrella to school."),
    seasons: makeUnit("Seasons", "季节", "🍂", "能介绍四季天气、衣着与喜欢的活动。", "spring:春天,summer:夏天,autumn:秋天,winter:冬天,warm:温暖的,cool:凉爽的,snow:雪,season:季节,pick:采摘,fly a kite:放风筝", ["Which season do you like?|你喜欢哪个季节？|which 用于有限选择。","I like spring best.|我最喜欢春天。|best 表示最。","We can fly kites in spring.|春天我们可以放风筝。|季节前用 in。"], "I like autumn best. The air is cool, the leaves are colorful and my family picks oranges together."),
    shopping: makeUnit("Shopping", "购物", "🛒", "能询问价格、数量并礼貌购买物品。", "shop:商店,buy:买,price:价格,yuan:元,cheap:便宜的,expensive:昂贵的,size:尺码,pair:一双,how much:多少钱,change:零钱", ["How much is it?|它多少钱？|询问单数物品价格。","It's thirty yuan.|三十元。|人民币单位 yuan 不加-s。","Can I try it on?|我可以试穿吗？|try on 表示试穿。"], "Lina needs a new hat. The blue one is thirty yuan. She tries it on and it fits well."),
    teachers: makeUnit("Teachers' Day", "教师节", "💐", "能描述老师并表达感谢和祝福。", "teacher:老师,kind:亲切的,helpful:乐于助人的,smile:微笑,card:卡片,flower:花,September:九月,thank:感谢,wish:祝愿,teach:教", ["Happy Teachers' Day!|教师节快乐！|节日名称首字母大写。","This flower is for you.|这朵花送给您。|for 表示给。","Thank you for helping me.|谢谢您帮助我。|Thank you for 后接名词或 doing。"], "Ms Lin is kind and helpful. Her students make a card and write a warm thank-you message."),
    trip: makeUnit("Planning a Trip", "旅行计划", "🧳", "能用将来表达旅行目的地、交通和准备。", "trip:旅行,plan:计划,train:火车,plane:飞机,ticket:票,hotel:酒店,camera:相机,map:地图,visit:参观,tomorrow:明天", ["Where will you go?|你将去哪里？|will + 动词原形表示将来。","I'll go to Xiamen.|我将去厦门。|I'll 是 I will 的缩写。","How will you go there?|你将怎样去那里？|how 询问方式。"], "On Saturday, Leo will visit Xiamen with his family. They will go by train and take a camera."),
    weekend: makeUnit("Weekend Activities", "周末活动", "🏸", "能谈论周末安排以及过去做过的事情。", "weekend:周末,cinema:电影院,museum:博物馆,park:公园,football:足球,visit:拜访,stay:停留,watch:观看,Saturday:星期六,Sunday:星期日", ["What do you do at the weekend?|你周末做什么？|at the weekend 表示在周末。","I often visit my grandma.|我经常看望奶奶。|often 常放在实义动词前。","Did you play football?|你踢足球了吗？|过去的一般疑问句用 Did。"], "At the weekend, Anna visits her grandma and helps in the garden. On Sunday afternoon, she plays badminton."),
    months: makeUnit("Months of the Year", "一年十二个月", "🗓️", "能认读月份、表达生日和简单日期。", "January:一月,February:二月,March:三月,April:四月,May:五月,June:六月,July:七月,August:八月,September:九月,October:十月,November:十一月,December:十二月", ["When is your birthday?|你的生日在什么时候？|when 询问时间。","It's in October.|在十月。|月份前用 in。","Which month comes after May?|五月之后是哪个月？|after 表示在……之后。"], "Tina's birthday is in October. She likes the cool weather and colorful autumn leaves."),
    directions: makeUnit("Asking the Way", "问路", "🗺️", "能礼貌问路并听懂基本方向指引。", "left:左边,right:右边,straight:直走,turn:转弯,street:街道,hospital:医院,station:车站,beside:在旁边,far:远的,way:路", ["Excuse me. Where is the library?|打扰一下，图书馆在哪里？|问路先说 Excuse me。","Go straight and turn left.|直走然后左转。|祈使句用动词原形。","It's beside the bank.|它在银行旁边。|beside 表示紧挨着。"], "A visitor asks Amy the way to the museum. She tells him to go straight and turn right at the school."),
    phone: makeUnit("Making Phone Calls", "打电话", "📞", "能用英语接打简单电话、留言和告别。", "call:打电话,phone:电话,hello:喂,speak:讲话,message:留言,wait:等待,busy:忙的,later:稍后,number:号码,bye:再见", ["May I speak to Sally?|我可以和萨莉通话吗？|电话中找人可用 May I speak to...?","This is Sally speaking.|我就是萨莉。|电话中自报身份不用 I am。","Can I take a message?|我能帮忙留言吗？|take a message 表示捎口信。"], "Ben calls Sally, but she is busy. Her brother takes a message and asks Ben to call again later."),
    friends: makeUnit("My Friends", "我的朋友", "🧑‍🤝‍🧑", "能描述朋友的外貌、性格和爱好。", "tall:高的,short:矮的,strong:强壮的,thin:瘦的,quiet:安静的,clever:聪明的,helpful:乐于助人的,glasses:眼镜,hair:头发,friend:朋友", ["What does he look like?|他长什么样？|询问外貌。","He is tall and strong.|他又高又强壮。|be 后接形容词。","He likes playing basketball.|他喜欢打篮球。|like 后可接 doing。"], "My friend Kai is tall and wears glasses. He is quiet in class, but he is helpful and funny."),
    vacation: makeUnit("Winter Vacation", "寒假生活", "⛄", "能谈论寒假中已经发生的活动。", "vacation:假期,travel:旅行,visit:拜访,played:玩了,watched:观看了,went:去了,took:拍摄了,photo:照片,wonderful:精彩的,yesterday:昨天", ["How was your winter vacation?|你的寒假怎么样？|询问过去用 was。","It was wonderful.|非常精彩。|was 是 is 的过去式。","I went to Beijing.|我去了北京。|went 是 go 的过去式。"], "During the winter vacation, Eva went to Quanzhou. She visited an old street and took many photos."),
    zoo: makeUnit("A Visit to the Zoo", "参观动物园", "🦒", "能描述参观动物园的经历和动物动作。", "zoo:动物园,giraffe:长颈鹿,penguin:企鹅,kangaroo:袋鼠,behind:在后面,near:在附近,jump:跳,walk:走,saw:看见了,funny:有趣的", ["What animals did you see?|你看见了什么动物？|did 后动词用原形。","I saw two pandas.|我看见两只熊猫。|saw 是 see 的过去式。","The bear was behind the tree.|熊在树后面。|behind 描述位置。"], "At the zoo, Sam saw two giraffes and three penguins. A little monkey jumped near the tree."),
    easter: makeUnit("Easter Eggs", "复活节彩蛋文化", "🥚", "能了解彩蛋活动并描述制作步骤。", "Easter:复活节,egg:蛋,hide:藏,find:寻找,paint:涂色,basket:篮子,colorful:多彩的,chocolate:巧克力,first:首先,next:接着", ["Let's paint the eggs.|我们给蛋涂色吧。|Let's 提议一起做。","First, wash the eggs.|首先，把蛋洗干净。|first/next 表示步骤。","Where did you hide it?|你把它藏在哪里？|did 后用动词原形。"], "First, the children paint six eggs. Next, Dad hides them in the garden. Everyone looks for the colorful eggs."),
    outing: makeUnit("A Spring Outing", "春游", "🌼", "能制定春游计划并介绍携带物品。", "outing:郊游,grass:草地,mountain:山,water:水,bread:面包,camera:相机,umbrella:雨伞,meet:集合,leave:出发,enjoy:享受", ["We are going for an outing.|我们要去春游。|be going to 表示计划。","What are you going to take?|你准备带什么？|询问计划携带物品。","I'll take some water.|我会带一些水。|不可数名词前可用 some。"], "The class is going for a spring outing. Mia will take water, bread and a small camera."),
    sports: makeUnit("Sports Day", "运动会", "🏃", "能谈论运动项目、比赛结果和鼓励他人。", "race:赛跑,long jump:跳远,high jump:跳高,run:跑,win:获胜,try:尝试,fast:快的,strong:强壮的,team:队,cheer:加油", ["Who will run the 100 meters?|谁将参加100米跑？|will 后接动词原形。","I will try my best.|我会尽最大努力。|try one's best 表示尽力。","Come on!|加油！|用于比赛中鼓励。"], "On Sports Day, Ming runs in the 100-meter race. His classmates cheer, and he tries his best to finish."),
    feelings: makeUnit("Feelings", "感受与情绪", "😊", "能识别情绪、说明原因并关心他人。", "happy:高兴的,sad:难过的,angry:生气的,tired:疲劳的,afraid:害怕的,worried:担心的,proud:自豪的,feel:感觉,why:为什么,because:因为", ["How do you feel?|你感觉怎么样？|how 用来询问状态。","I feel worried.|我感到担心。|feel 后接形容词。","Why? — Because I lost my bag.|为什么？—因为我丢了书包。|because 说明原因。"], "Nora feels worried because she cannot find her pencil case. Her friend helps her look under the desk."),
    buildings: makeUnit("Tall Buildings", "高楼与城市", "🏙️", "能比较建筑物高度、楼层和城市地点。", "building:建筑物,floor:楼层,lift:电梯,stairs:楼梯,tall:高的,higher:更高的,highest:最高的,city:城市,office:办公室,view:景色", ["Which building is taller?|哪栋楼更高？|两者比较用 taller。","This is the tallest building.|这是最高的建筑。|三者以上用 the tallest。","The office is on the fifth floor.|办公室在五楼。|序数词表示楼层。"], "The library has six floors. From the top floor, Leo can see the river and many city streets."),
    dates: makeUnit("Dates of the Month", "月份日期", "📆", "能认读序数词并准确表达日期。", "first:第一,second:第二,third:第三,fourth:第四,fifth:第五,eighth:第八,ninth:第九,twelfth:第十二,date:日期,calendar:日历", ["What's the date today?|今天几号？|询问日期用 date。","It's May 5th.|今天是5月5日。|日期用序数词读。","The test is on June 2nd.|考试在6月2日。|具体日期前用 on。"], "The school show is on June 2nd. Amy marks the date on her calendar and starts to practise."),
    olympics: makeUnit("The Olympic Games", "奥林匹克运动会", "🏅", "能介绍奥运项目、国家与运动精神。", "Olympics:奥运会,game:比赛,medal:奖牌,athlete:运动员,team:队,country:国家,swimming:游泳,basketball:篮球,proud:自豪的,peace:和平", ["When did the Games begin?|奥运会什么时候开始？|did 后动词用原形。","They take place every four years.|每四年举行一次。|take place 表示举行。","I'm proud of the athletes.|我为运动员自豪。|be proud of 表示为……自豪。"], "Athletes from many countries meet at the Olympic Games. They compete, make friends and respect one another."),
    exercise: makeUnit("Physical Exercises", "体育锻炼", "🤸", "能谈论锻炼习惯、频率和健康益处。", "exercise:锻炼,jog:慢跑,swim:游泳,skip:跳绳,stretch:伸展,strong:强壮的,healthy:健康的,every day:每天,once:一次,twice:两次", ["How often do you exercise?|你多久锻炼一次？|how often 询问频率。","I exercise twice a week.|我每周锻炼两次。|次数 + a week 表频率。","Exercise makes us strong.|锻炼让我们强壮。|make + 人 + 形容词。"], "Liam jogs twice a week and skips rope every day. Exercise helps him sleep well and feel strong."),
    health: makeUnit("Food and Health", "饮食与健康", "🍎", "能区分健康食物并提出饮食建议。", "healthy:健康的,unhealthy:不健康的,energy:能量,sugar:糖,salt:盐,vegetable:蔬菜,fruit:水果,water:水,enough:足够的,habit:习惯", ["We should eat more vegetables.|我们应该多吃蔬菜。|should 后接动词原形。","Don't eat too much sugar.|不要吃太多糖。|不可数名词用 too much。","Is this food healthy?|这种食物健康吗？|healthy 是形容词。"], "A healthy lunch has vegetables, rice and some protein. Water is a better everyday drink than a sweet drink."),
    buyclothes: makeUnit("Buying New Clothes", "买新衣服", "👕", "能描述服装、询问尺码价格并做选择。", "jacket:夹克衫,trousers:裤子,dress:连衣裙,size:尺码,large:大号,small:小号,fit:合身,try on:试穿,cost:花费,comfortable:舒适的", ["What size do you wear?|你穿多大尺码？|what size 询问尺码。","May I try this on?|我可以试穿这件吗？|this 指单数近处物品。","It fits me well.|它很合身。|fit 表示大小合适。"], "Nina tries on a green jacket. It fits well and feels comfortable, so she chooses it."),
    housework: makeUnit("Housework", "家务劳动", "🧹", "能说出常见家务并谈论家庭分工。", "sweep:扫,mop:拖地,wash:洗,cook:做饭,tidy:整理,room:房间,dishes:餐具,laundry:洗衣物,help:帮助,together:一起", ["Can you help me with the housework?|你能帮我做家务吗？|help...with... 表示帮助做。","I'll wash the dishes.|我来洗碗。|I'll 可表示主动承担。","We cleaned the room together.|我们一起打扫了房间。|cleaned 是过去式。"], "On Saturday, everyone helps at home. Dad cooks, Mum does the laundry and the children tidy their rooms."),
    unusual: makeUnit("An Unusual Day", "不寻常的一天", "🌪️", "能按顺序讲述一次过去的特别经历。", "unusual:不寻常的,happened:发生了,woke:醒来,rain:雨,missed:错过,found:找到,finally:最后,suddenly:突然,then:然后,lucky:幸运的", ["What happened yesterday?|昨天发生了什么？|happened 是过去式。","First..., then..., finally...|首先……然后……最后……|连接词让叙述有顺序。","I missed the bus.|我错过了公交车。|missed 是规则过去式。"], "Yesterday was unusual. Kai woke up late and missed the bus, but a kind neighbor gave him a ride."),
    thanksgiving: makeUnit("Thanksgiving", "感恩节文化", "🦃", "能了解感恩主题并用英语表达感谢。", "Thanksgiving:感恩节,turkey:火鸡,harvest:收获,family:家人,meal:一餐,thankful:感激的,share:分享,invite:邀请,celebrate:庆祝,tradition:传统", ["What are you thankful for?|你感激什么？|be thankful for 表示因……感激。","I'm thankful for my family.|我感激我的家人。|for 后接感谢的对象。","They share a special meal.|他们分享特别的一餐。|share 表示共同享用。"], "At Thanksgiving, a family shares a special meal. Each person says one thing they are thankful for."),
    universe: makeUnit("The Universe", "宇宙", "🚀", "能谈论太阳系、星球和太空探索。", "universe:宇宙,space:太空,planet:行星,Earth:地球,Moon:月球,Sun:太阳,star:恒星,rocket:火箭,astronaut:宇航员,travel:旅行", ["The Earth goes around the Sun.|地球绕太阳运行。|专有名词 Earth/Sun 首字母大写。","Is the Moon a planet?|月球是行星吗？|一般疑问句把 is 提前。","Astronauts travel into space.|宇航员进入太空。|into 表示进入。"], "Earth is our home in space. It goes around the Sun, and the Moon goes around Earth."),
    winter: makeUnit("Winter Activities", "冬季活动", "⛷️", "能谈论过去的冬季活动和感受。", "winter:冬天,snowman:雪人,ski:滑雪,skate:滑冰,cold:寒冷的,snowy:下雪的,played:玩了,made:制作了,went:去了,fun:乐趣", ["What did you do in winter?|冬天你做了什么？|did 后用动词原形。","I made a snowman.|我堆了雪人。|made 是 make 的过去式。","Did you go skating?|你去滑冰了吗？|回答 Yes, I did./No, I didn't."], "It snowed during Mia's trip. She made a small snowman and went skating with her cousin."),
    helping: makeUnit("Helping Each Other", "互相帮助", "🤝", "能表达关心、提供帮助并说明擅长科目。", "help:帮助,hospital:医院,carry:搬运,lesson:功课,worry:担心,hear:听见,better:更好的,fruit:水果,visit:探望,kind:善良的", ["I'm sorry to hear that.|听到这个消息我很难过。|用于听到不好的消息。","Can I help you with math?|我能帮助你学数学吗？|help...with... 表示帮助某方面。","Don't worry.|别担心。|don't + 动词原形构成否定祈使句。"], "Wang is in hospital with a hurt leg. His friends visit him, bring fruit and help with his lessons."),
    doctor: makeUnit("Seeing a Doctor", "看医生", "🩺", "能描述身体不适、听懂医生建议。", "headache:头痛,fever:发烧,cough:咳嗽,cold:感冒,matter:问题,medicine:药,rest:休息,water:水,doctor:医生,feel:感觉", ["What's the matter?|怎么了？|询问身体状况。","I have a headache.|我头痛。|have a + 症状。","You should have a good rest.|你应该好好休息。|should 表示建议。"], "Leo has a fever and a cough. The doctor asks him to rest, drink water and take the medicine on time."),
    motherday: makeUnit("Mother's Day", "母亲节", "💗", "能表达对家人的爱并计划一份心意。", "Mother's Day:母亲节,card:卡片,flower:花,breakfast:早餐,surprise:惊喜,love:爱,thank:感谢,make:制作,give:给予,May:五月", ["What will you do for Mum?|你会为妈妈做什么？|will 表达计划。","I'll make a card for her.|我会给她做一张卡片。|for her 表示给她。","Thank you for everything.|谢谢您做的一切。|真诚表达感谢。"], "On Mother's Day, Ava makes breakfast and a small card. The gift is simple, but her mother loves it."),
    occupation: makeUnit("Occupation", "职业", "👩‍⚕️", "能询问并介绍家人的职业和工作地点。", "doctor:医生,nurse:护士,teacher:老师,farmer:农民,worker:工人,driver:司机,cook:厨师,office:办公室,hospital:医院,farm:农场", ["What does your father do?|你爸爸做什么工作？|询问职业常用这一句。","He's a doctor.|他是一名医生。|职业单数前用 a/an。","Where does he work?|他在哪里工作？|does 后动词用原形。"], "Mia's aunt is a nurse. She works in a hospital and helps many people every day."),
    dream: makeUnit("Dream Job", "梦想职业", "🌟", "能谈论未来理想职业并说明理由。", "dream:梦想,scientist:科学家,pilot:飞行员,artist:艺术家,writer:作家,engineer:工程师,job:工作,future:未来,become:成为,good at:擅长", ["What do you want to be?|你想成为什么？|want to be 后接职业。","I want to be a scientist.|我想成为科学家。|职业前用 a/an。","Because I'm good at science.|因为我擅长科学。|be good at 后接名词或 doing。"], "Evan loves asking questions and doing experiments. He wants to become a scientist in the future."),
    middleschool: makeUnit("A Visit to a Middle School", "参观中学", "🎓", "能描述校园参观并比较小学与中学生活。", "middle school:中学,lab:实验室,hall:礼堂,canteen:食堂,subject:学科,student:学生,guide:向导,different:不同的,larger:更大的,excited:兴奋的", ["The school is larger than ours.|这所学校比我们的更大。|比较级 + than。","There is a science lab.|有一间科学实验室。|单数用 there is。","We were excited to visit it.|我们很兴奋去参观。|were 是 are 的过去式。"], "The sixth graders visit a middle school. A student guide shows them the lab, library and sports hall."),
    farewell: makeUnit("Farewell", "毕业告别", "🎒", "能回顾小学生活、表达感谢并送上祝福。", "farewell:告别,graduate:毕业,memory:回忆,miss:想念,remember:记得,wish:祝愿,future:未来,friendship:友谊,thank:感谢,keep in touch:保持联系", ["I'll miss you.|我会想念你。|will 表达将来的感受。","Thank you for helping me.|谢谢你帮助我。|for 后接 doing。","Let's keep in touch.|让我们保持联系。|用于毕业告别。"], "At the farewell party, the students share photos and happy memories. They thank their teachers and promise to keep in touch.")
  };

  const book = (id, grade, term, label, edition, keys) => ({ id, grade, term, label, edition, units: keys.map((key, index) => ({ ...U[key], id: `${id}-u${index + 1}`, number: index + 1 })) });

  window.COURSE_BOOKS = [
    book("g3a", 3, "上册", "三年级上册", "2024新课标主题", ["meeting","numbers","colors","family"]),
    book("g3b", 3, "下册", "三年级下册", "2024新课标主题", ["animals","clothes","food","happy"]),
    book("g4a", 4, "上册", "四年级上册", "2024新课标主题", ["school","daily","hobbies","festivals"]),
    book("g4b", 4, "下册", "四年级下册", "闽教版核心主题", ["weekly","classroom","animalnumbers","time","shopping","weather","seasons","springfestival"]),
    book("g5a", 5, "上册", "五年级上册", "闽教版核心主题", ["meeting","teachers","trip","weekend","months","directions","phone","friends"]),
    book("g5b", 5, "下册", "五年级下册", "闽教版核心主题", ["vacation","zoo","easter","outing","sports","feelings","buildings","dates"]),
    book("g6a", 6, "上册", "六年级上册", "闽教版核心主题", ["olympics","exercise","health","buyclothes","housework","unusual","thanksgiving","universe"]),
    book("g6b", 6, "下册", "六年级下册", "闽教版核心主题", ["winter","helping","doctor","motherday","occupation","dream","middleschool","farewell"])
  ];
})();
